# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: default
type: Opaque
data:
  mariadb_user: YWRtaW4=
  mariadb_passwd: QWRtaW4xMjM0
  mariadb_root_passwd: cm9vdA==
---
