# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vidz
  namespace: default
  labels:
    app: vidz
spec:
  selector:
    matchLabels:
      app: vidz
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container:  vidz
      labels:
        app: vidz
    spec:
      containers:
      - name: vidz
        image: ckefa/vidz_img:3
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        env:
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: mariadb-config
              key: mariadb_host
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mariadb-secret 
              key: mariadb_user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret 
              key: mariadb_passwd
        - name: MYSQL_DB
          valueFrom:
            configMapKeyRef:
              name: mariadb-config
              key: mariadb_name
        ports:
        - containerPort: 5000
          name: vidz
      restartPolicy: Always
---

# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: vidz
  namespace: default
spec:
  selector:
    app: vidz
  type: ClusterIP
  ports:
  - name: vidz
    protocol: TCP
    port: 80
    targetPort: 5000
---

